/**
 *
 *  RestfulSkusCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulSkusCtrl.h"
#include <string>



void RestfulSkusCtrl::get(const HttpRequestPtr &req,
                          std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulSkusCtrlBase::get(req, std::move(callback));
}

void RestfulSkusCtrl::create(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulSkusCtrlBase::create(req, std::move(callback));
}
