/**
 *
 *  RestfulSkusCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulSkusCtrlBase.h"

#include "Skus.h"
using namespace drogon;
using namespace drogon_model::example;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the skus table.
 */

class RestfulSkusCtrl: public drogon::HttpController<RestfulSkusCtrl>, public RestfulSkusCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulSkusCtrl::get,"/skus",Get,Options);
    ADD_METHOD_TO(RestfulSkusCtrl::create,"/skus",Post,Options);
    //ADD_METHOD_TO(RestfulSkusCtrl::update,"/skus",Put,Options);
    METHOD_LIST_END
     
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
