/**
 *
 *  RestfulUserCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulUserCtrl.h"
#include <string>


void RestfulUserCtrl::getOne(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback,
                             User::PrimaryKeyType &&id)
{
    RestfulUserCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulUserCtrl::updateOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                User::PrimaryKeyType &&id)
{
    RestfulUserCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulUserCtrl::deleteOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                User::PrimaryKeyType &&id)
{
    RestfulUserCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulUserCtrl::get(const HttpRequestPtr &req,
                          std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulUserCtrlBase::get(req, std::move(callback));
}

void RestfulUserCtrl::create(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulUserCtrlBase::create(req, std::move(callback));
}
