/**
 *
 *  RestfulProductsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulProductsCtrlBase.h"

#include "Products.h"
using namespace drogon;
using namespace drogon_model::example;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the products table.
 */

class RestfulProductsCtrl: public drogon::HttpController<RestfulProductsCtrl>, public RestfulProductsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulProductsCtrl::getOne,"/products/{1}",Get,Options);
    ADD_METHOD_TO(RestfulProductsCtrl::updateOne,"/products/{1}",Put,Options);
    ADD_METHOD_TO(RestfulProductsCtrl::deleteOne,"/products/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulProductsCtrl::get,"/products",Get,Options);
    ADD_METHOD_TO(RestfulProductsCtrl::create,"/products",Post,Options);
    //ADD_METHOD_TO(RestfulProductsCtrl::update,"/products",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Products::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Products::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Products::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
