/**
 *
 *  RestfulCartsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulCartsCtrlBase.h"

#include "Carts.h"
using namespace drogon;
using namespace drogon_model::example;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the carts table.
 */

class RestfulCartsCtrl: public drogon::HttpController<RestfulCartsCtrl>, public RestfulCartsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulCartsCtrl::getOne,"/carts/{1}",Get,Options);
    ADD_METHOD_TO(RestfulCartsCtrl::updateOne,"/carts/{1}",Put,Options);
    ADD_METHOD_TO(RestfulCartsCtrl::deleteOne,"/carts/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulCartsCtrl::get,"/carts",Get,Options);
    ADD_METHOD_TO(RestfulCartsCtrl::create,"/carts",Post,Options);
    //ADD_METHOD_TO(RestfulCartsCtrl::update,"/carts",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Carts::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Carts::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Carts::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
