/**
 *
 *  RestfulCartsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulCartsCtrl.h"
#include <string>


void RestfulCartsCtrl::getOne(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback,
                              Carts::PrimaryKeyType &&id)
{
    RestfulCartsCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulCartsCtrl::updateOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Carts::PrimaryKeyType &&id)
{
    RestfulCartsCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulCartsCtrl::deleteOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Carts::PrimaryKeyType &&id)
{
    RestfulCartsCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulCartsCtrl::get(const HttpRequestPtr &req,
                           std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulCartsCtrlBase::get(req, std::move(callback));
}

void RestfulCartsCtrl::create(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulCartsCtrlBase::create(req, std::move(callback));
}
