/**
 *
 *  RestfulReviewsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulReviewsCtrlBase.h"

#include "Reviews.h"
using namespace drogon;
using namespace drogon_model::example;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the reviews table.
 */

class RestfulReviewsCtrl: public drogon::HttpController<RestfulReviewsCtrl>, public RestfulReviewsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulReviewsCtrl::getOne,"/reviews/{1}",Get,Options);
    ADD_METHOD_TO(RestfulReviewsCtrl::updateOne,"/reviews/{1}",Put,Options);
    ADD_METHOD_TO(RestfulReviewsCtrl::deleteOne,"/reviews/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulReviewsCtrl::get,"/reviews",Get,Options);
    ADD_METHOD_TO(RestfulReviewsCtrl::create,"/reviews",Post,Options);
    //ADD_METHOD_TO(RestfulReviewsCtrl::update,"/reviews",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Reviews::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Reviews::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Reviews::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
