/**
 *
 *  RestfulProductsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulProductsCtrl.h"
#include <string>


void RestfulProductsCtrl::getOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Products::PrimaryKeyType &&id)
{
    RestfulProductsCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulProductsCtrl::updateOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Products::PrimaryKeyType &&id)
{
    RestfulProductsCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulProductsCtrl::deleteOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Products::PrimaryKeyType &&id)
{
    RestfulProductsCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulProductsCtrl::get(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulProductsCtrlBase::get(req, std::move(callback));
}

void RestfulProductsCtrl::create(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulProductsCtrlBase::create(req, std::move(callback));
}
